<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./static/crate.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import {AutoColliders} from '@threlte/rapier'

  export const ref = new Group()

  const gltf = useGltf('/crate.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={0.5}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <AutoColliders shape="cuboid" >
    <T.Mesh geometry={gltf.nodes.Box.geometry} >
      <T.MeshPhysicalMaterial color="orange" />
    </T.Mesh>
  </AutoColliders>

  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
