<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./static/fence.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/fence.glb')
  export let rotated = false;

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} scale={0.5} scale.y={0.5} scale.x={0.5}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  {#if rotated}
  <T.Mesh 
  geometry={gltf.nodes.Fence002.geometry}
  material={gltf.materials['Material.008']}
  position={[-1.79, 0, -0.03]}
  rotation.x={-Math.PI / 2} 
  />
  {:else}
    <T.Mesh 
    geometry={gltf.nodes.Fence002.geometry}
    material={gltf.materials['Material.008']}
    position={[-1.79, 0, 0.03]}
   />
  {/if}
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
